import { NextRequest, NextResponse } from 'next/server'
import { PrismaClient } from '@prisma/client'
import { getServerSession } from 'next-auth'

const prisma = new PrismaClient()

function buildReportHtml(site: any, logs: any[], period: string, user: any) {
  const published = logs.filter(l => l.action === 'publish_post' && l.status === 'success').length
  const aiChats   = logs.filter(l => l.action === 'ai_chat').length
  const changes   = logs.filter(l => l.category === 'ai_action' && l.status === 'success').length
  const snapshots = logs.filter(l => l.action === 'snapshot').length

  const companyName = user.wlCompanyName || 'ignyous.ai'

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
  body{font-family:system-ui,sans-serif;color:#1a1a2e;background:#f8f9fc;margin:0;padding:0}
  .wrap{max-width:600px;margin:0 auto;padding:32px 24px}
  .header{background:linear-gradient(135deg,#1a1a4e,#2d2d7a);color:white;padding:32px;border-radius:16px;margin-bottom:24px;text-align:center}
  .header h1{margin:0 0 6px;font-size:24px}
  .header p{margin:0;opacity:.7;font-size:14px}
  .grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-bottom:24px}
  .stat{background:white;border-radius:12px;padding:20px;box-shadow:0 1px 4px rgba(0,0,0,.06);text-align:center}
  .stat .n{font-size:32px;font-weight:800;color:#1a1a4e}
  .stat .l{font-size:13px;color:#6b7280;margin-top:4px}
  .log{background:white;border-radius:12px;padding:20px;box-shadow:0 1px 4px rgba(0,0,0,.06);margin-bottom:24px}
  .log h3{margin:0 0 14px;font-size:15px;color:#1a1a4e}
  .entry{display:flex;gap:10;align-items:flex-start;padding:8px 0;border-bottom:1px solid #f3f4f6;font-size:13px}
  .entry:last-child{border-bottom:none}
  .dot{width:8px;height:8px;border-radius:50%;background:#22c55e;flex-shrink:0;margin-top:4px}
  .dot.fail{background:#ef4444}
  .footer{text-align:center;font-size:12px;color:#9ca3af;margin-top:24px}
</style>
</head><body>
<div class="wrap">
  <div class="header">
    <h1>📊 Monthly Site Report</h1>
    <p>${site.name || site.url} · ${period}</p>
  </div>

  <div class="grid">
    <div class="stat"><div class="n">${changes}</div><div class="l">Changes Made</div></div>
    <div class="stat"><div class="n">${published}</div><div class="l">Posts Published</div></div>
    <div class="stat"><div class="n">${aiChats}</div><div class="l">AI Interactions</div></div>
    <div class="stat"><div class="n">${snapshots}</div><div class="l">Backups Taken</div></div>
  </div>

  <div class="log">
    <h3>Recent Activity</h3>
    ${logs.slice(0, 12).map(l => `
    <div class="entry">
      <div class="dot ${l.status === 'failed' ? 'fail' : ''}"></div>
      <div>
        <strong>${l.summary || l.action}</strong>
        <span style="color:#9ca3af"> · ${new Date(l.timestamp).toLocaleDateString([], { month: 'short', day: 'numeric' })}</span>
      </div>
    </div>`).join('')}
  </div>

  <div class="footer">
    Report generated by ${companyName} · <a href="${process.env.NEXTAUTH_URL || 'https://ignyous.ai'}">View Dashboard</a>
  </div>
</div>
</body></html>`
}

// POST — generate and optionally send a report
export async function POST(req: NextRequest) {
  const session = await getServerSession()
  if (!session?.user?.email) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { siteId, send: sendEmail = false } = await req.json()
  const user = await prisma.user.findUnique({ where: { email: session.user.email } })
  const site = await prisma.site.findFirst({ where: { id: siteId, userId: user?.id } })
  if (!site) return NextResponse.json({ error: 'Site not found' }, { status: 404 })

  const since  = new Date(Date.now() - 30 * 86400000)
  const logs   = await prisma.activityLog.findMany({
    where: { siteUrl: site.url, timestamp: { gte: since } },
    orderBy: { timestamp: 'desc' },
    take: 100,
  })

  const period = new Date().toLocaleDateString([], { month: 'long', year: 'numeric' })
  const html   = buildReportHtml(site, logs, period, user)

  if (sendEmail) {
    const to = user?.reportEmail || user?.email
    if (to && process.env.RESEND_API_KEY) {
      await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${process.env.RESEND_API_KEY}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({
          from: `${user?.wlCompanyName || 'ignyous'} <reports@ignyous.ai>`,
          to: [to],
          subject: `📊 Monthly Report — ${site.name || site.url} — ${period}`,
          html,
        }),
      })
    }
  }

  return NextResponse.json({ success: true, html, period, logCount: logs.length })
}

// GET — report settings
export async function GET() {
  const session = await getServerSession()
  if (!session?.user?.email) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  const user = await prisma.user.findUnique({ where: { email: session.user.email } })
  return NextResponse.json({ reportEmail: user?.reportEmail, reportEnabled: user?.reportEnabled })
}
