<?php
namespace Ignyous\Baseline\Themes;

use Ignyous\Baseline\Snapshots;

/**
 * Astra theme adapter.
 *
 * Astra stores its settings in a single 'astra-settings' option (serialized array).
 * Common keys we handle:
 *
 *   - 'theme-color'             string  primary brand color
 *   - 'link-color'              string  link color (Astra also reuses theme-color in many places)
 *   - 'link-h-color'            string  link hover color
 *   - 'text-color'              string  body text color
 *   - 'site-content-bg-color'   string  content background
 *   - 'font-family-h1'…'h6'     string  per-heading font family (Astra calls these "Headings 1-6")
 *   - 'headings-font-family'    string  global heading font family (Astra 4.x)
 *   - 'body-font-family'        string  body font family (Astra 4.x)
 *
 * Astra reads from this option on every page load — no separate cache to bust
 * for the common settings. Their compiled CSS is regenerated by Astra's own
 * filter chain whenever the option changes.
 *
 * Background_color: Astra uses different keys for site-vs-content bg. For Phase 5
 * we map background_color → site-content-bg-color since that's what most users mean.
 */
class AstraAdapter extends ThemeAdapter {

    const OPTION_KEY = 'astra-settings';

    public function slug(): string { return 'astra'; }
    public function name(): string { return 'Astra'; }

    public function matches(string $stylesheet, string $template): bool {
        if ($template === 'astra' || $stylesheet === 'astra') return true;
        if (defined('ASTRA_THEME_VERSION')) return true;
        return false;
    }

    public function capabilities(): array {
        return [
            'primary_color'    => true,
            'text_color'       => true,
            'background_color' => true,
            'link_color'       => true,
            'heading_font'     => true,
            'body_font'        => true,
        ];
    }

    public function read(): array {
        $opt = $this->getSettings();
        return [
            'current' => [
                'primary_color'    => $this->str($opt, 'theme-color'),
                'text_color'       => $this->str($opt, 'text-color'),
                'background_color' => $this->str($opt, 'site-content-bg-color'),
                'link_color'       => $this->str($opt, 'link-color'),
                'heading_font'     => $this->getFontFamily($opt, 'headings'),
                'body_font'        => $this->getFontFamily($opt, 'body'),
            ],
            'raw' => [
                'option_key' => self::OPTION_KEY,
                'astra_version' => defined('ASTRA_THEME_VERSION') ? ASTRA_THEME_VERSION : null,
                'settings_keys' => is_array($opt) ? array_keys($opt) : [],
            ],
        ];
    }

    public function patch(array $body, string $changeId): array {
        $before  = $this->getSettings();
        $next    = is_array($before) ? $before : [];
        $applied = [];
        $errors  = [];

        if (array_key_exists('primary_color', $body)) {
            $v = $this->sanitizeColor($body['primary_color']);
            if ($v) {
                $next['theme-color'] = $v;
                $next['link-color']  = $v;                       // common default cascade
                $next['button-color']      = $this->contrastingTextColor($v);
                $next['button-bg-color']   = $v;
                $next['button-h-color']    = $this->contrastingTextColor($v);
                $next['button-bg-h-color'] = $this->darken($v, 0.12);
                $applied['primary_color'] = $v;
            } else $errors['primary_color'] = 'invalid_color';
        }
        if (array_key_exists('text_color', $body)) {
            $v = $this->sanitizeColor($body['text_color']);
            if ($v) { $next['text-color'] = $v; $applied['text_color'] = $v; }
            else    $errors['text_color'] = 'invalid_color';
        }
        if (array_key_exists('background_color', $body)) {
            $v = $this->sanitizeColor($body['background_color']);
            if ($v) { $next['site-content-bg-color'] = $v; $applied['background_color'] = $v; }
            else    $errors['background_color'] = 'invalid_color';
        }
        if (array_key_exists('link_color', $body)) {
            $v = $this->sanitizeColor($body['link_color']);
            if ($v) { $next['link-color'] = $v; $applied['link_color'] = $v; }
            else    $errors['link_color'] = 'invalid_color';
        }
        if (array_key_exists('heading_font', $body)) {
            $v = trim((string) $body['heading_font']);
            $this->setFontFamily($next, 'headings', $v);
            $applied['heading_font'] = $v;
        }
        if (array_key_exists('body_font', $body)) {
            $v = trim((string) $body['body_font']);
            $this->setFontFamily($next, 'body', $v);
            $applied['body_font'] = $v;
        }

        // Snapshot the whole option (compact JSON) so undo is one restore
        $beforeJson = wp_json_encode($before ?: new \stdClass());
        $snapId = Snapshots::open($changeId, 'option', self::OPTION_KEY, $beforeJson, 'Astra settings');
        $ok     = update_option(self::OPTION_KEY, $next);
        Snapshots::close($snapId, wp_json_encode($next));

        // Astra has a dynamic CSS cache option; clear known cache keys if present
        delete_option('astra-settings-cached-dynamic-css');
        if (function_exists('astra_clear_all_assets_cache')) {
            astra_clear_all_assets_cache();
        }

        $after = $this->getSettings();
        return [
            'applied'      => $applied,
            'errors'       => $errors,
            'snapshot_ids' => [$snapId],
            'current'      => [
                'primary_color'    => $this->str($after, 'theme-color'),
                'text_color'       => $this->str($after, 'text-color'),
                'background_color' => $this->str($after, 'site-content-bg-color'),
                'link_color'       => $this->str($after, 'link-color'),
                'heading_font'     => $this->getFontFamily($after, 'headings'),
                'body_font'        => $this->getFontFamily($after, 'body'),
            ],
            'success' => $ok || empty($errors),
        ];
    }

    // --------------------------------------------------------------- helpers

    private function getSettings(): array {
        $v = get_option(self::OPTION_KEY, []);
        return is_array($v) ? $v : [];
    }

    private function str(array $opt, string $k): ?string {
        if (!isset($opt[$k])) return null;
        $v = $opt[$k];
        return is_string($v) ? $v : (is_scalar($v) ? (string) $v : null);
    }

    /**
     * Astra font storage (verified against Astra 4.x source):
     *   - Body font:     'body-font-family'      (NOT 'font-family-body')
     *   - Heading font:  'headings-font-family'  (NOT 'font-family-headings')
     *   - Per-heading overrides also exist: 'font-family-h1'..'h6'.
     * We read the global key first, then fall back to per-heading slots.
     */
    private function getFontFamily(array $opt, string $which): ?string {
        if ($which === 'body') return $this->str($opt, 'body-font-family');
        // headings
        if (isset($opt['headings-font-family'])) return $this->str($opt, 'headings-font-family');
        for ($i = 1; $i <= 6; $i++) {
            $key = 'font-family-h' . $i;
            if (isset($opt[$key])) return $this->str($opt, $key);
        }
        return null;
    }

    private function setFontFamily(array &$opt, string $which, string $value): void {
        if ($which === 'body') {
            $opt['body-font-family'] = $value;
            return;
        }
        $opt['headings-font-family'] = $value;
        for ($i = 1; $i <= 6; $i++) {
            $opt['font-family-h' . $i] = $value;
        }
    }

    /** Slightly darker variant for button-hover. Returns hex; falls back to input on non-hex. */
    private function darken(string $hex, float $amt): string {
        $h = ltrim($hex, '#');
        if (strlen($h) === 3) $h = $h[0].$h[0].$h[1].$h[1].$h[2].$h[2];
        if (strlen($h) < 6) return $hex;
        $r = max(0, (int) (hexdec(substr($h, 0, 2)) * (1 - $amt)));
        $g = max(0, (int) (hexdec(substr($h, 2, 2)) * (1 - $amt)));
        $b = max(0, (int) (hexdec(substr($h, 4, 2)) * (1 - $amt)));
        return sprintf('#%02x%02x%02x', $r, $g, $b);
    }
}
